export function createPackageRoutes({readBody,json,sendEvent,resolveWorkspacePath,searchPiPackages,fetchPackageDetails,runPiPackageAction,configurePackageResources,inspectPackageSource,inspectPiPlatform}){
 return async function handlePackageRoutes(req,res,url){const{pathname,searchParams}=url;
  if(req.method==='GET'&&pathname==='/api/pi-packages/search'){const packages=await searchPiPackages(searchParams.get('q')||'',{resourceType:searchParams.get('type')||'',limit:Number(searchParams.get('limit')||20)});json(res,200,{ok:true,packages});return true;}
  if(req.method==='GET'&&pathname==='/api/pi-packages/details'){json(res,200,{ok:true,package:await fetchPackageDetails(searchParams.get('name')||'',{version:searchParams.get('version')||''})});return true;}
  if(req.method==='POST'&&pathname==='/api/pi-packages/inspect-source'){const body=await readBody(req);let workspace=body.workspace||'';if(body.scope==='project'&&workspace){const resolved=await resolveWorkspacePath(workspace,'.');workspace=resolved.root;}json(res,200,{ok:true,provenance:await inspectPackageSource(body.source,{workspace,scope:body.scope||'project'})});return true;}
  if(req.method==='POST'&&['/api/pi-packages/install','/api/pi-packages/update','/api/pi-packages/remove'].includes(pathname)){const body=await readBody(req);let workspace=body.workspace||'';if(body.scope==='project'){const resolved=await resolveWorkspacePath(workspace,'.');workspace=resolved.root;}const action=pathname.split('/').pop();const result=await runPiPackageAction(action,{...body,workspace});sendEvent('pi_platform_changed',{workspace,kind:'package',action,source:result.source,scope:result.scope});json(res,200,{ok:true,result,platform:workspace?await inspectPiPlatform(workspace):null});return true;}
  if(req.method==='PUT'&&pathname==='/api/pi-packages/config'){const body=await readBody(req);let workspace=body.workspace||'';if(body.scope==='project'){const resolved=await resolveWorkspacePath(workspace,'.');workspace=resolved.root;}const result=await configurePackageResources(workspace,body);sendEvent('pi_platform_changed',{workspace,kind:'package-config',source:body.source,scope:body.scope});json(res,200,{ok:true,result,platform:workspace?await inspectPiPlatform(workspace):null});return true;}
  return false;
 };
}
